services:
  # sonu_web_ai_prod:
  #   image: image
  #   ports:
  #     - ${USER_PORT}:3000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - db_nw
  #     - web_nw
  #   restart: unless-stopped

  postgres:
    image: postgres:16.3
    command: postgres -c 'max_connections=200'
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - new-db:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - prod-docker.env
    networks:
      - db_nw

  # redis:
  #   image: redis:7-alpine
  #   restart: always
  #   ports:
  #     - 6380:6379
  #   networks:
  #     - web_nw
  #   env_file:
  #     - prod-docker.env

  # app_nginx:
  #   image: nginx:latest
  #   container_name: nginx_sonu_web_ai_prod
  #   restart: always
  #   volumes:
  #     - ./cfg/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 8890:80
  #   networks:
  #     - web_nw
  #   depends_on:
  #     - sonu_web_ai_prod

volumes:
  new-db:
    driver: local

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
